export const ENVIRONMENT = {
  CLINICS_DATA_DB_PASSWORD: process.env.CLINICS_DATA_DB_PASSWORD,
  CLINICS_DATA_DB_HOST: process.env.CLINICS_DATA_DB_HOST,
  CLINICS_DATA_DB_USER: process.env.CLINICS_DATA_DB_USER,
  CLINICS_DATA_DB_NAME: process.env.CLINICS_DATA_DB_NAME,
  CLINICS_DATA_DB_PORT: process.env.CLINICS_DATA_DB_PORT,
}